### ISSUE TITLE
ASSERT(ctr->counter < INTERNAL_OPTION(trace_threshold)): monitor.c:2242

### ISSUE THREAD

**Issue by raghuncstate** [DynamoRIO/dynamorio#2989]
Continuing from the google users thread at https://groups.google.com/forum/#!topic/dynamorio-users/85AegFB0kps

I am attempting to run the Java JVM binary under DR with a java application and am seeing crashes unless i turn off the JIT with the -XInt option. This is on x86-64. I have attached a zip file with images of DR crashes, and instructions on how to reproduce the issue. The crashes are fairly easy to reproduce once everything is setup.

Please let me know if there is any way i can help in debugging the issue or if you require further information. Due to my limited exposure to DR internals so far, the precise crash locations does not provide enough context for me to debug this further.
[crash_package.zip](https://github.com/DynamoRIO/dynamorio/files/1969065/crash_package.zip)

**Comment by raghuncstate** [comment]
Not sure if the attachment was missed. crash_package.zip in the post above contains the minimized test case and a readme file to reproduce the issue along with some screen shots of the crash/asserts.
Please let me know if you are unable to reproduce the issue or if you would like dumps or logs for the issue.

**Comment by raghuncstate** [comment]
Updates per bug reporting guidelines. Information below is also present in the readme file in the attached zip file.
1) Images - In crash_package.zip linked above. (If this is not acceptable and it must be on google drive or another location please let me know).
2)  Setup information:
        Application: Tomcat 7.0.86 on Java JRE 8.0_171
        OS : Windows 10 Pro, Windows Server 2012
        DR Version: DR build on windows with commit 864e453e04702 and no code changes. Built using cmake-gui with all default options selected, except built the debug version.

Following are the asserts seen on different runs with different drrun.exe options:
1) drrun.exe -debug: ASSERT(ctr->counter < INTERNAL_OPTION(trace_threshold))
2) drrun.exe -debug: ASSERT(!info.overlap || (f != NULL && TEST(FRAG_IS_TRACE, f->flags)));
3) drrun.exe -debug -thread_private: ASSERT(area_contains_frag_pc(area, entry));

**Comment by dannykim32** [comment]
Any update on this?

**Comment by Carrotman42** [comment]
As far as I can tell, no one from the DR has had the opportunity to look into this problem.

From the detailed posts from raghuncstate last year (thanks!) it seems that a common theme in the assertion is "traces" and other strangeness related to the generated code DR emits. Another flag to try would be `--disable_traces`.

We have fixed numerous bugs in the past year, some for generic systems and some others for Windows; I believe Linux-based systems have been put under the microscope a little more often recently, though. Has anyone tried getting it to work on a linux-based JVM instead?

Also, it would be nice to get a more minimal reproducer which is based on official software releases and specific source code which can be read through before running; I do not want to download a random zip file from the Internet and execute it on my computer :)

**Comment by derekbruening** [comment]
As the users thread noted, the Ion and V8 JVM's worked fine under DR in the past.  One avenue of investigation would be to try those today and see whether this is a regression or something specific to the particular JVM you are running.

Experimental improved JIT handling was done in the past and we are looking for a volunteer to integrate it into the main branch: see https://github.com/DynamoRIO/dynamorio/wiki/JIT-Optimization.  It is improving performance of JITs, but it may also eliminate area-tracking problems (assert number 3).

Other options to try would be `-no_hw_cache_consistency` and `-no_sandbox_writes` just to get more data on where the problem(s) lie.

I would echo @Carrotman42 and start by disabling traces `-disable_traces` and focus on issues hit there first, to simplify things.  If a problem is reproducible and happens early (i.e., a log won't be huuuge) use `-loglevel 4` to get detailed info on exactly what is going on.  See also https://github.com/DynamoRIO/dynamorio/wiki/Debugging for further tips.

**Comment by dannykim32** [comment]
I have tried running a simple java program under drrun.exe that simply is adding random numbers together in a loop (iterating 10,000,000) times and I see that dynamorio still crashes (not everytime, but a non-trivial number of times). 

I believe the issue is that dynamorio's code cache loses coherency with the JVM's internal code cache (on its own heap used for compiled methods/dyn gen code). I am running the latest version of Dynamorio and have tried running my simple java program with jdk8 and jdk12. I've attached my simple code here. 

Anyone run into this issue? I've seen dynamorio crash while trying to run other java programs as well on any windows machine I've tested (Windows server 2012, windows 10). I'd love to get just a better idea of what is going on. I've tried to run drrun with disable_traces as well.

[arrays.java.txt](https://github.com/DynamoRIO/dynamorio/files/3114015/arrays.java.txt)

**Comment by derekbruening** [comment]
Unfortunately It is tough for the small number of core DR developers to spend significant time on issues not related to our day jobs and there are a lot of such things (everything Windows or Mac, e.g., as well as Java).  If this is high priority for @raghuncstate and @dannykim32 it will likely be fixed more quickly if you take the lead.  We are happy to consult and advise of course.

**Comment by derekbruening** [comment]
I hit this same assert in an RSEQ test after changing the rseq instrumentation for #4019 .

Here is what happens:

```
F1938 counter is now 50
Going to start trace with F1938 (tag 0x00007ff81ae8da79)

mangle: inserting native rseq code 0x00007fc7f033ca4e
Fragment 1978, tag 0x00007fc7f033ca79, flags 0x20806b0, private temp, size 250, cannot be trace:

Entry into F1938(0x00007ff81ae8da79).0x00007ff7daf1b318 (trace head)(shared)
        
Exit from F1938(0x00007ff81ae8da79).0x00007ff7daf1b40b (shared) 
 (cannot link F1938->F1939) (target F1939 is trace head)

d_r_dispatch: target = 0x00007ff81ae8da8d
F1939 counter is now 50
Going to start trace with F1939 (tag 0x00007ff81ae8da8d)
...
Ending and emitting hot trace (tag 0x00007ff81ae8da8d)
...
Exit from F1975(0x00007f268dae7a0c).0x00007f264db07892 (shared) 
 (cannot link F1975->F1938) (target F1938 is trace head)

d_r_dispatch: target = 0x00007f268dae7a79
SYSLOG_ERROR: Application /home/bruening/dr/git/build_x64_dbg_tests/suite/tests/bin/linux.rseq (59689).  Internal Error: DynamoRIO debug check failure: /home/bruening/dr/git/src/core/monitor.c:2222 ctr->counter < INTERNAL_OPTION(trace_threshold)
(Error occurred @1992 frags)
```

So we have a bb made into a trace head whose counter crosses 50.  But the temp private copy we make is marked FRAG_CANNOT_BE_TRACE!  It's due to pad_jmps: it has a different start alignment than the original and it ends up needing a nop inserted, for which we do not support traces (#4038).  The code fails to decrement the counter in that case, so the next time we hit it the assert fires.

There are multiple bad things here: the nondeterministic cannot-be-trace (#4038); failing to handle the sudden change (this issue: the assert); the lack of progress even if we fix the assert; the lack of IBL targeting in general of FRAG_CANNOT_BE_TRACE.

The workaround is `-disable_traces`.

**Comment by derekbruening** [comment]
As for why Java would hit this I'm not sure: selfmod exits should end up already FRAG_CANNOT_BE_TRACE.  Maybe just inlined syscalls??  Some of the original filers would have to check.
